GLSP-984 Improve WebSocket launching
eclipse-glsp/glsp-theia-integration pull request #159
Opened 2023-05-23 10:25 UTC by tortmayr

- Refactor `GLSPSocketServerContribution` to enable fine grained configuration of the used websocket address
   - Remove default `webSocketPath` parsing and provide utility function that can be used by implementing contributions instead. Similar to how its done for port parsing
- Rename webSocket path argument used in the example to `WF_PATH` to be inline with the example port argument
- Refactor `GLSPClientContribution` to enable better support for the direct websocket usecase
   - Ensure that we don't create an unused service connection if in directWS mode
   - Remove "hacks/workarounds" in TheiaJsonRPCClient
   - Refactor `doActivate` method to handle both usecases
- Improve performance of `WebsocketConnectionForwarder` by directly sending buffers instead of converting them to strings before.

2023-05-23 10:25 UTC, tortmayr commented
@ndoschek  FYI

2023-05-30 08:43 UTC, martin-fleck-at requested changes
Change looks good to me, thank you for the great work, Tobias!

I only suggest to remove the commented line and we need to rebase the change. Otherwise, we are good to go.

2023-05-30 08:43 UTC, martin-fleck-at commented on packages/theia-integration/src/node/glsp-socket-server-contribution.ts
> +    // protected webSocketAddress?: string;
```suggestion

```

2023-05-30 09:55 UTC, martin-fleck-at approved these changes
LGTM!

2023-05-30 09:59 UTC, merged